apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-1
data:
  ID: 1
  QUEUESIZE: 9
  TARGETS: service-0,service-2
  DELAYS: 3,3
  TRANSFORMS: 0.77,0.59
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymet-1
spec:
  replicas: 1
  selector:
    matchLabels:
      id: 1
  template:
    metadata:
      labels:
        id: 1
    spec:
      containers:
      - name: service
        image: service
        ports:
        - containerPort: 80
      envFrom:
      - configMapRef:
          name: configmap-1
---
apiVersion: v1
kind: Service
metadata:
  name: service-1
spec:
  selector:
    app.kubernetes.io/name: deployment-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
