apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-2
data:
  ID: 2
  QUEUESIZE: 13
  TARGETS: service-3,service-1
  DELAYS: 4,3
  TRANSFORMS: 1.22,1.22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymet-2
spec:
  replicas: 1
  selector:
    matchLabels:
      id: 2
  template:
    metadata:
      labels:
        id: 2
    spec:
      containers:
      - name: service
        image: service
        ports:
        - containerPort: 80
      envFrom:
      - configMapRef:
          name: configmap-2
---
apiVersion: v1
kind: Service
metadata:
  name: service-2
spec:
  selector:
    app.kubernetes.io/name: deployment-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
