apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-15
data:
  TARGETS: service-14
  DELAYS: 1
  TRANSFORMS: 1.0519075240917406
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymet-15
spec:
  replicas: 1
  selector:
    matchLabels:
      id: 15
  template:
    metadata:
      labels:
        id: 15
    spec:
      containers:
      - name: service
        image: service
        ports:
        - containerPort: 80
      envFrom:
      - configMapRef:
          name: configmap-15
---
apiVersion: v1
kind: Service
metadata:
  name: service-15
spec:
  selector:
    app.kubernetes.io/name: deployment-15
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
