apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-3
data:
  ID: 3
  QUEUESIZE: 9
  TARGETS: service-2,service-4,service-19
  DELAYS: 1,4,2
  TRANSFORMS: 0.69,1.26,0.71
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymet-3
spec:
  replicas: 1
  selector:
    matchLabels:
      id: 3
  template:
    metadata:
      labels:
        id: 3
    spec:
      containers:
      - name: service
        image: service
        ports:
        - containerPort: 80
      envFrom:
      - configMapRef:
          name: configmap-3
---
apiVersion: v1
kind: Service
metadata:
  name: service-3
spec:
  selector:
    app.kubernetes.io/name: deployment-3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
