apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-8
data:
  ID: 8
  QUEUESIZE: 7
  TARGETS: service-7,service-9
  DELAYS: 1,3
  TRANSFORMS: 1.16,1.30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymet-8
spec:
  replicas: 1
  selector:
    matchLabels:
      id: 8
  template:
    metadata:
      labels:
        id: 8
    spec:
      containers:
      - name: service
        image: service
        ports:
        - containerPort: 80
      envFrom:
      - configMapRef:
          name: configmap-8
---
apiVersion: v1
kind: Service
metadata:
  name: service-8
spec:
  selector:
    app.kubernetes.io/name: deployment-8
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
