apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-8
data:
  TARGETS: service-7,service-9,service-10,service-11,service-12
  DELAYS: 4,2,1,3,4
  TRANSFORMS: 1.3185673059449123,0.8494804218293566,0.5132960690659548,0.9862395258217262,0.8892869009015926
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymet-8
spec:
  replicas: 1
  selector:
    matchLabels:
      id: 8
  template:
    metadata:
      labels:
        id: 8
    spec:
      containers:
      - name: service
        image: service
        ports:
        - containerPort: 80
      envFrom:
      - configMapRef:
          name: configmap-8
---
apiVersion: v1
kind: Service
metadata:
  name: service-8
spec:
  selector:
    app.kubernetes.io/name: deployment-8
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
