apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-10
data:
  ID: 10
  QUEUESIZE: 8
  TARGETS: service-15,service-16,service-9,service-11,service-12,service-13,service-14
  DELAYS: 3,3,1,3,2,2,5
  TRANSFORMS: 1.34,0.87,0.55,1.04,0.58,1.17,0.63
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymet-10
spec:
  replicas: 1
  selector:
    matchLabels:
      id: 10
  template:
    metadata:
      labels:
        id: 10
    spec:
      containers:
      - name: service
        image: service
        ports:
        - containerPort: 80
      envFrom:
      - configMapRef:
          name: configmap-10
---
apiVersion: v1
kind: Service
metadata:
  name: service-10
spec:
  selector:
    app.kubernetes.io/name: deployment-10
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
