apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-12
data:
  TARGETS: service-8,service-13
  DELAYS: 1,2
  TRANSFORMS: 0.5701610960571282,0.7752057099732528
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymet-12
spec:
  replicas: 1
  selector:
    matchLabels:
      id: 12
  template:
    metadata:
      labels:
        id: 12
    spec:
      containers:
      - name: service
        image: service
        ports:
        - containerPort: 80
      envFrom:
      - configMapRef:
          name: configmap-12
---
apiVersion: v1
kind: Service
metadata:
  name: service-12
spec:
  selector:
    app.kubernetes.io/name: deployment-12
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
