apiVersion: apps/v1
kind: Deployment
metadata:
  name: coletor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coletor
  template:
    metadata:
      labels:
        app: coletor
    spec:
      containers:
      - name: coletor
        image: coletor
        imagePullPolicy: Never
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb:27017"
        - name: POLL_INTERVAL
          value: "30"
        - name: TEST_MODE
          value: "false"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: coletor
spec:
  selector:
    app: coletor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080