apiVersion: v1
kind: ConfigMap
metadata:
  name: sink-configmap
data:
  SOURCE: 'http://service-0'
  INTERVAL: '1.0'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sink
spec:
  replicas: 1
  selector:
    matchLabels:
      id: 2
  template:
    metadata:
      labels:
        id: 2
    spec:
      containers:
      - name: sink
        image: sink
        ports:
        - containerPort: 80
      envFrom:
      - configMapRef:
        name: sink-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: sink
spec:
  selector:
    app.kubernetes.io/name: sink
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
