version: '3.8'

services:
 app:
   build: .
   container_name: metrics_collector
   depends_on:
     - mongo
   environment:
     - MONGO_URI=mongodb://mongo:27017
   networks:
     - app-network

 mongo:
   image: mongo:5.0
   container_name: mongodb
   ports:
     - "27017:27017"
   networks:
     - app-network
   volumes:
     - mongo-data:/data/db

networks:
 app-network:
   driver: bridge

volumes:
 mongo-data: