# Use a imagem oficial do Go como base
FROM golang:1.23.4-alpine

# Defina o diretório de trabalho dentro do container
WORKDIR /app

# Copie todos os arquivos do projeto para o diretório de trabalho
COPY . .

# Inicialize o módulo Go
RUN go mod init coletor

# Baixe as dependências
RUN go get ./...

# Compile o programa Go
RUN go build -o coletor .

# Comando para executar o programa
CMD ["./coletor"]