apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-reader
subjects:
  - kind: ServiceAccount
    name: k8stopology-sa
    namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8stopology-sa
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: 'collector-configmap'
data:
  # MONGO_URI: 'mongodb://mongodb:27017'
  POLL_INTERVAL: "3"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      serviceAccountName: k8stopology-sa
      containers:
      - name: collector
        image: collector
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: 'collector-configmap'
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: collector
spec:
  selector:
    app: collector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mongodb
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mongodb
#   template:
#     metadata:
#       labels:
#         app: mongodb
#     spec:
#       containers:
#       - name: mongodb
#         image: mongo:latest
#         ports:
#         - containerPort: 27017
#         volumeMounts:
#         - name: mongo-data
#           mountPath: /data/db
#       volumes:
#       - name: mongo-data
#         persistentVolumeClaim:
#           claimName: mongo-pvc
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongodb
# spec:
#   selector:
#     app: mongodb
#   ports:
#     - protocol: TCP
#       port: 27017
#       targetPort: 27017
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mongo-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
